name: apex_network_take_home_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  hooks_riverpod: ^1.0.4

  # networking
  dio: ^4.0.6
  freezed_annotation:
  json_annotation: ^4.5.0

  # utilities
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.5.3+2
  flutter_hooks: ^0.18.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable:
  freezed:
  build_runner:
  logger: ^1.1.0

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sfprodisplay/SFProDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/sfprodisplay/SFProDisplay-BlackItalic.otf
          weight: 900
        - asset: assets/fonts/sfprodisplay/SFProDisplay-HeavyItalic.otf
          weight: 800
        - asset: assets/fonts/sfprodisplay/SFProDisplay-LightItalic.otf
          weight: 300
        - asset: assets/fonts/sfprodisplay/SFProDisplay-SemiBoldItalic.otf
          weight: 600
        - asset: assets/fonts/sfprodisplay/SFProDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/sfprodisplay/SFProDisplay-UltraLightItalic.otf
          weight: 200
        - asset: assets/fonts/sfprodisplay/SFProDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/sfprodisplay/SFProDisplay-ThinItalic.otf
          weight: 100
